name: Run Android Instrumented Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode keystore if needed (opcional)
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Run emulator and tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis_playstore
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-window -gpu swiftshader_indirect -no-audio
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
