name: Java CI with Maven + Appium (Android 10)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [29]         # Android 10
        target: [google_apis]
        profile: [Pixel_3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and Start Appium
        run: |
          npm install -g appium@v1.20.2
          nohup appium > appium.log 2>&1 &
          echo "Starting Appium..."
          for i in {1..10}; do
            if curl -s http://127.0.0.1:4723/wd/hub/status | grep -q '"ready":true'; then
              echo "✅ Appium is ready!"
              break
            fi
            echo "⌛ Waiting for Appium to be ready..."
            sleep 5
          done
          if ! curl -s http://127.0.0.1:4723/wd/hub/status | grep -q '"ready":true'; then
            echo "❌ Appium failed to start in time."
            cat appium.log
            exit 1
          fi

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: ${{ matrix.profile }}
          script: mvn clean test -Pandroid
